name: "Frogbot Scan Repository"
on:
  workflow_dispatch:
  schedule:
    # The repository will be scanned once a day at 00:00 GMT.
    - cron: "0 0 * * *"
permissions:
    contents: write
    pull-requests: write
    security-events: write
    id-token: write
jobs:
  frogbot:
    name: Run Frogbot
    runs-on: ubuntu-latest
    steps:
     -  uses: actions/checkout@v4
     -  uses: jfrog/frogbot@v2
        with:
          oidc-provider-name: jfrog-github-oidc
          version: latest
        env:
          JF_INSTALL_DEPS_CMD: "npm i"
          JF_URL: https://${{ vars.JF_URL }}/
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: main
          JF_WORKING_DIR: .
          JF_PATH_EXCLUSIONS: "*git*,*node_modules*,*target*,*venv*,*test*"
          JF_PROJECT: ${{ vars.JF_PROJECT }}
          JF_FAIL: FALSE